### ISSUE TITLE
Alpha feedback / first impressions

### ISSUE THREAD

**Issue by dsharp-pivotal** [IdeaGinkgo/Intellij-Ginkgo#1]
Hi! Thanks for taking the time to work on this. It's a great start, and will make development with Ginkgo nicer. Here were the most glaring issues I had when trying it out. Please let me know if you'd like me to create separate issues for any/all of these. Even just getting the first one worked out would make this usable for me.

- Looks for "ginkgo" in `$GOROOT/bin`, rather than `$GOBIN` or `$GOPATH/bin`.
  - That is, on my MacOS, it tries to run "/usr/local/Cellar/go/1.16.3/libexec/bin/ginkgo", instead of "$HOME/go/bin/ginkgo"
  - This means that I have to always edit the run configuration to fix the path to ginkgo.
- After running tests, I see "Test framework quit unexpectedly" in the sidebar rather than the descriptions of test cases run, even though the tests passed.
- Runs with `-r` (recursive), but this will end up attempting to run more than the expected tests (in subdirectories).
- When constructing the "--focus" string, ideally it should include the full test description, including from outer blocks. We often have multiple `It("succeeds")` in a file, for example. This results in running multiple tests instead of just one.
- Missing "When" in list of ginkgo node functions.
- "F" (Focus) and "X" (Pending) variants of nodes are not marked ("FIt", "XDescribe", etc), although not sure how useful that would be.

**Comment by TaylorOno** [comment]
Awesome thanks for the feedback.

- Looks for "ginkgo" in `$GOROOT/bin`, rather than `$GOBIN` or `$GOPATH/bin`.
  - This seems like something I can definitely fix.
- After running tests, I see "Test framework quit unexpectedly" in the sidebar rather than the descriptions of test cases run, even though the tests passed.
  - I'll give this my best shot the test results box is the item I was struggling with most.
- Runs with `-r` (recursive), but this will end up attempting to run more than the expected tests (in subdirectories).
  - Will fix so it only runs with the all tests config, my plan was to have have radial buttons in the test config for All, Suite, Focus options that way.
- When constructing the "--focus" string, ideally it should include the full test description, including from outer blocks. We often have multiple `It("succeeds")` in a file, for example. This results in running multiple tests instead of just one.
  - I agree but this will take some doing on my part and maybe somebody smart than me who has a clever transverse the tests structure.
- Missing "When" in list of ginkgo node functions.
  - Done.
- "F" (Focus) and "X" (Pending) variants of nodes are not marked ("FIt", "XDescribe", etc), although not sure how useful that would be.
  - I'll definitely start marking the "F" run markers, the "X" run markers I don't know should those be playable maybe a greyed out play icon?

**Comment by TaylorOno** [comment]
Do you want to give the latest version a shot?

**Comment by dsharp-pivotal** [comment]
I gave it a try with 0.0.3-alpha. Looks like several improvements!

However, focus is not working with "when" blocks for me. I think the issue is that, for `When` blocks only, ginkgo [prefixes the word "when"](https://github.com/onsi/ginkgo/blob/master/ginkgo_dsl.go#L369) before the block descriptions, but you're not doing the same to generate focus strings.

I wonder if this is also affecting the test pane (or maybe this is still WIP). In the test list, I'm only seeing grey "-" icons ("Test terminated") next to the (correct, ie with "when") test descriptions, and the last test is marked with a yellow "x" icon (Assertion failure), even though all tests are passing. It is able to show individual tests' output when clicking on an item.

---
I had an idea regarding tests focused with "F": Perhaps if there are any "F" blocks, all other blocks should be marked with a grey play icon.

**Comment by TaylorOno** [comment]
I think I got `when` block working focus working.. I know there is a problem with the test pane and `[Pending]` test marking things as terminated.  I'll have to do more testing to see if I can recreate the invalid assertion fail marker and only seeing grey "-" problems.

**Comment by dsharp-pivotal** [comment]
I tested out 0.1.0-beta. I can confirm the `When` block focus is working on my end. Looks like maybe you worked out the test pane issues as well, as that seems to be working too.

As far as I'm concerned, you've addressed all the issues I brought up initially, and the plugin is totally usable as it is now. Thanks again! I'm going to share this with my team now. 😄
